//! Memoized negamax solver on the compressed (first, last) edge-count multigraph.
//!
//! Key optimizations:
//! 1. **Reachability-restricted memo key**: only include edges reachable from the
//!    current required letter in the hash — often far fewer than all 119 non-zero pairs.
//! 2. **Retrograde shortcut**: query the 26-node letter-graph retrograde before any search.
//! 3. **Forced-move compression**: chain single-successor letters without memoizing intermediates.
//! 4. **Incremental Zobrist hashing**: O(1) hash update per move (vs hashing 676 bytes).
//! 5. **Move ordering**: try lowest-out-degree successors first (trap opponent).
//! 6. **Depth limit**: `can_win` returns `None` at the cutoff → callers fall back to rollout.

use rustc_hash::FxHashMap;

use crate::gen1::pair_index;
use crate::graph::LetterGraph;

// ---------------------------------------------------------------------------
// Zobrist table (generated deterministically at compile time via a simple LCG)
// ---------------------------------------------------------------------------

/// Maximum multiplicity any (first,last) pair can have.  Gen 1 max is 4; pad to 9.
const MAX_COUNT: usize = 9;

/// Flat table: `ZOBRIST[edge_idx * MAX_COUNT + count]` = random u64 for that (edge, count) pair.
/// Generated by a deterministic LCG so the binary is reproducible.
static ZOBRIST: std::sync::OnceLock<Vec<u64>> = std::sync::OnceLock::new();

fn zobrist() -> &'static [u64] {
    ZOBRIST.get_or_init(|| {
        let mut table = vec![0u64; 676 * MAX_COUNT];
        let mut state = 0x123456789abcdefu64;
        for v in &mut table {
            // xorshift64
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            *v = state;
        }
        table
    })
}

/// Initial Zobrist hash for a given counts array.
pub fn initial_hash(counts: &[u8; 676]) -> u64 {
    let z = zobrist();
    let mut h = 0u64;
    for idx in 0..676 {
        let c = counts[idx].min((MAX_COUNT - 1) as u8) as usize;
        if c > 0 {
            h ^= z[idx * MAX_COUNT + c];
        }
    }
    h
}

/// O(1) hash update when `counts[edge_idx]` changes from `old_c` to `new_c`.
#[inline]
pub fn update_hash(hash: &mut u64, edge_idx: usize, old_c: u8, new_c: u8) {
    let z = zobrist();
    let oc = (old_c as usize).min(MAX_COUNT - 1);
    let nc = (new_c as usize).min(MAX_COUNT - 1);
    if oc > 0 {
        *hash ^= z[edge_idx * MAX_COUNT + oc];
    }
    if nc > 0 {
        *hash ^= z[edge_idx * MAX_COUNT + nc];
    }
}

// ---------------------------------------------------------------------------
// Reachability-restricted hash
// ---------------------------------------------------------------------------

/// Hash only the edges whose source letter is in `reachable_mask`.
fn reachable_hash(counts: &[u8; 676], reachable_mask: u32) -> u64 {
    let z = zobrist();
    let mut h = 0u64;
    for u in 0u8..26 {
        if reachable_mask & (1 << u) == 0 {
            continue;
        }
        for v in 0u8..26 {
            let idx = pair_index(u, v);
            let c = (counts[idx] as usize).min(MAX_COUNT - 1);
            if c > 0 {
                h ^= z[idx * MAX_COUNT + c];
            }
        }
    }
    h
}

// ---------------------------------------------------------------------------
// Core solver
// ---------------------------------------------------------------------------

/// `true` = player to move wins; `false` = loses; `None` = depth limit reached.
pub fn can_win(
    required: Option<u8>,
    counts: &mut [u8; 676],
    graph: &mut LetterGraph,
    memo: &mut FxHashMap<(u8, u64), bool>,
    depth_limit: usize,
) -> Option<bool> {
    // -----------------------------------------------------------------------
    // Opening: unconstrained first move
    // -----------------------------------------------------------------------
    if required.is_none() {
        // No forced-move or retrograde short-circuit for the opening because any
        // (first, last) pair is legal — try them all.
        let labels = graph.retrograde();
        let mut winning = false;
        'outer: for f in 0u8..26 {
            for t in 0u8..26 {
                let idx = pair_index(f, t);
                if counts[idx] == 0 {
                    continue;
                }
                // If we play f→t, the opponent must start at t.
                // If retrograde says t is a Loser for the player-to-move (i.e. opponent) → we win.
                if labels[t as usize] == Some(false) {
                    return Some(true);
                }
                // Otherwise recurse (depth-limited).
                counts[idx] -= 1;
                graph.on_decrement(f, t, counts);
                let opp = can_win(Some(t), counts, graph, memo, depth_limit.saturating_sub(1));
                counts[idx] += 1;
                graph.on_increment(f, t);
                match opp {
                    Some(false) => {
                        winning = true;
                        break 'outer;
                    }
                    Some(true) => {}
                    None => {} // unknown; keep trying
                }
            }
        }
        return Some(winning);
    }

    let l = required.unwrap();

    // -----------------------------------------------------------------------
    // Forced-move compression: chain single-successor letters.
    // Track (f,t) pairs applied so we can undo them.
    // -----------------------------------------------------------------------
    let mut chain: Vec<(u8, u8)> = Vec::new();
    let mut cur = l;
    let mut parity = 0u8; // number of forced moves applied (mod 2)

    loop {
        // Retrograde check at current position in chain
        let labels = graph.retrograde();
        if let Some(win) = labels[cur as usize] {
            // Undo chain
            for &(f, t) in chain.iter().rev() {
                counts[pair_index(f, t)] += 1;
                graph.on_increment(f, t);
            }
            // win = is `cur` a winning start for the player to move *now*.
            // After `parity` forced moves, the original player moved parity times,
            // so the player now-to-move is the original player iff parity is even.
            return Some(win ^ (parity == 1));
        }

        // Count successors of `cur`
        let succ_mask = graph.successors[cur as usize];
        if succ_mask == 0 {
            // No moves → current player (at `cur`) loses.
            for &(f, t) in chain.iter().rev() {
                counts[pair_index(f, t)] += 1;
                graph.on_increment(f, t);
            }
            return Some(parity == 1); // if odd, the original player's opponent is stuck
        }

        // Check if exactly one distinct edge type is available from cur.
        // Count distinct target letters (bits) and total edge count.
        let distinct_targets = succ_mask.count_ones();
        if distinct_targets != 1 {
            break;
        } // branching point — stop compressing

        let t = succ_mask.trailing_zeros() as u8;
        // Apply the forced move.
        counts[pair_index(cur, t)] -= 1;
        graph.on_decrement(cur, t, counts);
        chain.push((cur, t));
        cur = t;
        parity ^= 1;
    }

    // -----------------------------------------------------------------------
    // Branching: memoized negamax
    // -----------------------------------------------------------------------
    let reachable = graph.reachable_from(cur);
    let h = reachable_hash(counts, reachable);
    let memo_key = (cur, h);

    let result = if let Some(&v) = memo.get(&memo_key) {
        v
    } else if depth_limit == 0 {
        // Undo chain before returning None
        for &(f, t) in chain.iter().rev() {
            counts[pair_index(f, t)] += 1;
            graph.on_increment(f, t);
        }
        return None;
    } else {
        // Build sorted move list: ascending out_degree of target (trapping moves first)
        let mut moves: Vec<(u8, u32)> = (0u8..26)
            .filter(|&t| counts[pair_index(cur, t)] > 0)
            .map(|t| (t, graph.out_degree[t as usize]))
            .collect();
        moves.sort_unstable_by_key(|&(_, od)| od);

        let mut winning = false;
        for (t, _) in moves {
            let idx = pair_index(cur, t);
            counts[idx] -= 1;
            graph.on_decrement(cur, t, counts);
            let opp = can_win(Some(t), counts, graph, memo, depth_limit - 1);
            counts[idx] += 1;
            graph.on_increment(cur, t);
            match opp {
                Some(false) => {
                    winning = true;
                    break;
                }
                Some(true) => {}
                None => {} // unknown
            }
        }
        memo.insert(memo_key, winning);
        winning
    };

    // Undo forced chain
    for &(f, t) in chain.iter().rev() {
        counts[pair_index(f, t)] += 1;
        graph.on_increment(f, t);
    }

    // Flip result based on parity of forced moves
    Some(result ^ (parity == 1))
}

/// All `(first, last)` pairs that are optimal opening plays.
/// Returns `(f, t, is_exact)` — `is_exact=false` if depth limit was hit for any branch.
pub fn optimal_opening_moves(
    counts: &mut [u8; 676],
    graph: &mut LetterGraph,
    memo: &mut FxHashMap<(u8, u64), bool>,
    depth_limit: usize,
) -> (Vec<(u8, u8)>, bool) {
    let mut out = Vec::new();
    let mut all_exact = true;
    for f in 0u8..26 {
        for t in 0u8..26 {
            let idx = pair_index(f, t);
            if counts[idx] == 0 {
                continue;
            }
            counts[idx] -= 1;
            graph.on_decrement(f, t, counts);
            let opp = can_win(Some(t), counts, graph, memo, depth_limit);
            counts[idx] += 1;
            graph.on_increment(f, t);
            match opp {
                Some(false) => out.push((f, t)),
                Some(true) => {}
                None => {
                    all_exact = false;
                }
            }
        }
    }
    (out, all_exact)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gen1;
    use rustc_hash::FxHashMap;

    fn fresh() -> FxHashMap<(u8, u64), bool> {
        FxHashMap::default()
    }

    #[test]
    fn trivial_no_moves_loses() {
        let mut c = [0u8; 676];
        let mut g = LetterGraph::from_counts(&c);
        let mut memo = fresh();
        assert_eq!(can_win(None, &mut c, &mut g, &mut memo, 1000), Some(false));
    }

    #[test]
    fn single_aa_edge_opening_wins() {
        let mut c = [0u8; 676];
        let a = 0u8;
        c[pair_index(a, a)] = 1; // a→a
        let mut g = LetterGraph::from_counts(&c);
        let mut memo = fresh();
        // Player 1 plays a→a; opponent must start with a; no moves left → opponent loses.
        assert_eq!(can_win(None, &mut c, &mut g, &mut memo, 1000), Some(true));
    }

    #[test]
    fn dead_letter_required_loses_immediately() {
        let mut c = [0u8; 676];
        let b = 1u8;
        let c_l = 2u8;
        c[pair_index(b, c_l)] = 1;
        let mut g = LetterGraph::from_counts(&c);
        let mut memo = fresh();
        // Must start with 'a' but only b→c exists
        let a = 0u8;
        assert_eq!(
            can_win(Some(a), &mut c, &mut g, &mut memo, 1000),
            Some(false)
        );
    }

    #[test]
    fn chain_of_forced_moves() {
        // a→b, b→c (both singletons) — player 1 plays a→b, player 2 forced b→c,
        // player 1 needs c→? but none → player 1 loses (2 forced moves = even parity)
        let mut c = [0u8; 676];
        let (a, b, cc) = (0u8, 1u8, 2u8);
        c[pair_index(a, b)] = 1;
        c[pair_index(b, cc)] = 1;
        let mut g = LetterGraph::from_counts(&c);
        let mut memo = fresh();
        // Required=a: only move is a→b; then b→c is forced; then c has no moves → current player (at c) loses.
        // c is at parity=2 (2 forced moves from a). parity even → result for required=a = false.
        assert_eq!(
            can_win(Some(a), &mut c, &mut g, &mut memo, 1000),
            Some(false)
        );
    }

    #[test]
    fn immediate_trap_wins() {
        // a→q, a→b: 'q' has no successors, 'b' goes on.
        // Player starting at a can play a→q and opponent is stuck.
        let mut c = [0u8; 676];
        let (a, b, q) = (0u8, 1u8, 16u8); // q=16
        c[pair_index(a, q)] = 1; // a→q (dead end)
        c[pair_index(a, b)] = 1;
        c[pair_index(b, a)] = 1;
        let mut g = LetterGraph::from_counts(&c);
        let mut memo = fresh();
        assert_eq!(
            can_win(Some(a), &mut c, &mut g, &mut memo, 1000),
            Some(true)
        );
    }

    #[test]
    fn gen1_small_opening_terminates() {
        // Use first 5 Pokémon — all first moves end in letters with no starters → first player wins
        let names: Vec<String> = gen1::load_gen1_names().into_iter().take(5).collect();
        let mut c = gen1::counts_from_names(&names);
        let mut g = LetterGraph::from_counts(&c);
        let mut memo = fresh();
        let result = can_win(None, &mut c, &mut g, &mut memo, 1000);
        assert_eq!(
            result,
            Some(true),
            "first 5 Pokémon: all openings reach dead letter"
        );
    }
}
